version: '3.7'

services:
  web:
    build:
      context: .
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      API_URL: 'https://scription-api-staging.herokuapp.com/api/v1'
